### PR TITLE
Fix example

### PR DESCRIPTION
**Pull request by domna**
- [x] Bump pynxtools>=0.3.3 as soon as it's released

### CODE REVIEW

**Comment by RonHildebrandt** [comment]
So, with these changes the ellipsometry reader is ready as pynxtools was updated to 0.4.0. CICD was fixed, as i missed, that for the CICD a different eln_data file was used, than the one I modified. This is fixed now!

**Comment by domna** [comment]
Looks good from my side. When you're happy feel free to approve and merge (I cannot do it since I initially created this PR).

**Comment by domna** [comment]
But I think you have to generate the requirements again because you were missing a space in the command, so it didn't pick up the extras properly

**Review by RonHildebrandt — APPROVED** [review]
Example is fixed with new pynxtools version. All required fixed to the CI/CD are finally done. Sounds good

**Pull request merged**
